Generated Files
^^^^^^^^^^^^^^^

* The +constants.go+ file, which contains all constants.
* The +ttypes.go+, which contains type definitions.

-----------------------------------------------------------------------------
$ tree gen-go
`-- thrift
    `-- example
        |-- constants.go
        `-- ttypes.go
-----------------------------------------------------------------------------

[TIP]
.Naming with Go Go命名规则
=============================================================================
The Go language uses capitalization to determine export rules. The Go thrift

Go语言使用大写字母来确定导出规则。Go thrift库会根据此规则调整名字.

library adapts thrift names to adhere to this convention. So a struct

所以一个名为 +userName+ 的结构字段将在Go中以 +UserName+ 的形式访问.

field called +userName+ will be accessible in Go as +UserName+. As a rule, the

通常情况下，任何常量或结构字段的第一个字母将被大写。

first letter of any constant or struct field will be capitalized.
=============================================================================

Types
^^^^^

Thrift maps the various base and container types to Go types as follows:

Thrift基类型和容器类型与Go类型的映射如下:

* +bool+: +bool+
* +binary+: +[]byte+
* +byte+: +byte+
* +i16+: +int16+
* +i32+: +int32+
* +i64+: +int64+
* +double+: +float64+
* +string+: +string+
* +list<t1>+: +[]t1+
* +set<t1>+: +map[t1]bool+ where +bool+ is always +true+
* +map<t1,t2>+: +map[t1]t2+

With the exception of +set+, which has no direct Go equivalent, all of the
types are straightforward.

除了 +set+ 之外, 其余的类型在Go语言中都有直接的对应.

The Thrift developers decided that the best way to represent Thrift +set+ types
in Go was to implement them as +map[t1]bool+.

Thrift开发人员决定代表Thrift +set+ 类型的最佳方式是实现为 +map[t1]bool+.

Typedefs
^^^^^^^^

Thrift typedefs are implemented in Go as Go types. Thus +typedef i32 MyInt+
becomes the Go +type MyInt int32+.

Thrift typedefs 是由 Go types 实现的.

Enums
^^^^^

The Go Thrift compiler translates enums to constants. The strategy it employs
is to create a set of constants where the +enum+ name is the prefix and the
+enum+ item's name is the suffix. The two are separated by an underscore (+_+).

Go Thrift编译器将枚举翻译为常数. 所采用的策略就是创建一组常数. 以 +enum+ 名字作为前缀,
+enum+ 元素的名字作为后缀, 并由下划线(+_+)来分割.

The +TweetType+ of +TWEET+ becomes, in Go, +TweetType_TWEET+.

例如, +TweetType+ 的 +TWEET+ 在Go为 +TweetType_TWEET+

Constants
^^^^^^^^^

Thrift constants are declared +const+ for Go types that can be declared as
constants (e.g. +int+, +string+, etc.). For types that cannot be declared 
+const+ (like maps and slices), the Go library declares these as global +var+.

对于可以被声明为常数的类型(例如, +int+, +string+ 等),
Thrift将其声明为 +const+.

对于不可以被声明为 +const+ 的类型(例如, maps and slices), Go声明其为全局 +var+.

Structs
^^^^^^^

The Thrift +struct+ is translated to Go +struct+ differently than in other
language libraries.

Unlike most Thrift implementations, the type declarations are substantially
impacted by whether or not a thrift attribute is declared +required+ or
+optional+. To distinguish between an empty value and a +nil+ value, the
Go library uses pointers for all +optional+ values.

Thrift +struct+ 转换为Go +struct+ 的方式与其他语言中的不一样.
不像多数Thrift实现, 类型申明基本上由Thrift属性是 +required+ 还是 +optional+ 决定.
为了区别空值和 +nil+, Go使用指针来表示所有 +optional+ 值.

For example, here is an abbreviated listing of the +Tweet+ struct discussed
above:

[source,thrift]
--------------------------------------------------------------------------------
struct Tweet {
  1: required i32 userId
  // ...
  4: optional Location loc
  // ...
}
--------------------------------------------------------------------------------

In Go, the field +userId+ will be +UserId int32+, while +loc+ will be
+Loc *Location+. The salient detail is that any field tagged as +optional+
will be implemented as a Go pointer to a value, while +required+ types are
implemented as values.

在Go中, +userId+ 会使用 +UserId int32+ . 然而, +loc+ 会使用 +Loc *Location+.
最突出的特点就是多有的 +optional+ 将会有Go指针实现, 而 +required+ 类型则会实现为值.

Unions
^^^^^^

Thrift +union+ types are translated into Go structs, where only one field on
the struct may be set to a non-nil value.

Thrift +union+ 会转换成Go结构体, 其中只有一个字段可以被设置成non-nil值.

